### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by SpicyWasab**
Hi !

Here's a new pull request for the French translation.

I'm unsure about a few things :
- Should I translate "Mousam" ? 😅
- A few other little things (mostly about the length of some strings, or their context). I'll made a review when it gets implemented in the app !

Have a nice day !

### CODE REVIEW

**Comment by amit9838** [comment]
No, nouns(mousam) are not translated 🙂 ,
Huh, Some sentences are longer (more than 2x) , i'm not sure how it is going to fit into the UI, can you share some Screenshots.

**Comment by SpicyWasab** [comment]
Alright ! I just wasn't sure about the origin of "Mousam", if it meant "weather" in some unknown language or anything.
(where does the name come from btw ?)

When you say "share some screenshots", you mean actually building the app from the code source to take a look at the translated UI ?

**Comment by amit9838** [comment]
Mousam means weather in Hindi,
About screenshots, if you have set dev environment , you can share the screenshots, otherwise no issue 🙂

**Comment by SpicyWasab** [comment]
Ohh, alright !

I've just cloned my repo and opened it with Gnome Builder.
I can run the app, however I'm not sure how to get the translated UI from my `.po` file, if I should link the file somewhere or anything.

**Comment by LukaszH77** [comment]
@SpicyWasab In Builder you have to `Build` the app first, then you can `Export` it to a flatpak package and install it. Let me know if you need more detailed instructions.

**Comment by SpicyWasab** [comment]
Hi again, I wasn't much available the few past days.
(today's my 18th birthday btw :partying_face:)

Thanks for the instructions. I also figured I forgot to link my `fr_FR.po` file in the `LINGUAS` file ^^'

Some strings were clearly to long, so I managed to shorten them. Here's a screenshot.
image

However, as you can see, some parts of the UI are still in english. I tried to see if I somehow tempered with their msgid, but they're not different from the ones listed in the original `mousam.pot` file. Furthermore, I also tried to look for the `_("string id")` gettext calls, and it's the same msgids as well.

Do you have any idea why the top and right cards aren't translated ?

**Comment by amit9838** [comment]
On this grand day, as the clock ticks to mark your 18th orbit around the sun, let the universe applaud your arrival into adulthood! 🎉 Embrace the journey ahead with zest, courage, and a sprinkle of stardust, for you are destined for greatness! 🌟 Happy Birthday @SpicyWasab !

**Comment by SpicyWasab** [comment]
Here's the translated ui so far.
The only untranslated things are :
1. "Day High" and "Day Max", aren't translated because they're not called with the gettext function in `frontendHourlyDetails.py` (actually, "Day Max" isn't defined in mousam.pot) ;
2. "Light Rain Showers", there's no entry for it in mousam.pot.

Even though python isn't my favourite language, I guess I could easily fix these alongside this pull request if you want.

image

image

**Comment by SpicyWasab** [comment]
I'm gonna sleep (it's actually 3:33), so I may not answer before a few hours :')

**Comment by amit9838** [comment]
Talking about the pr 😂, .pot file is updated with the valuable contribution of @LukaszH77 , he has added strings with context, maybe now you can translate it better.  Take your time, celebrate your Birthday 🎂 - Good Luck

**Comment by SpicyWasab** [comment]
Hi, thanks !
I read your message a while ago but I was kind of busy after that.

I'm gonna work on it right now, hopefully I'll make another PR / update this one in a few hours c:

**Comment by amit9838** [comment]
@SpicyWasab hope you are doing good, actually i'm planning to release the app very soon so it would be nice if you can translate the remaining strings. Thanks

**Comment by SpicyWasab** [comment]
> @SpicyWasab hope you are doing good, actually i'm planning to release the app very soon so it would be nice if you can translate the remaining strings. Thanks

Yeah thanks, hope you're doing good as well !

Oh, I didn't noticed some strings were untranslated.
I'm going to check this out, probably tomorrow morning !

**Comment by SpicyWasab** [comment]
Now that I'm digging more into the file, I honestly feel like the previous guy used google translate to translate ^^'
Mostly because some strings seems to be litteral translation, so I was a bit suspicious.
But, I mean, paying attention to the beginning of the file...

image

The comments and the legals got translated as well.
They didn't even put their name in the "Last-Translator: FULL NAME" line, they put the french translated equivalent of "FULL NAME" instead :')

**Comment by amit9838** [comment]
Yes, He hasn't  translated before this. Sure i'll ask him to add his name and email in the .po file for German.
Thanks for translating remaining strings. 🙂 .
Merging the pr.
This pr was stuck for too long 😆.

**Review by amit9838 — APPROVED** [review]
lgtm

**Comment by SpicyWasab** [comment]
Fine, thanks for taking the time to ask him for his name and email !
Granting some recognition to translators is important imo.

Yeah, it was open for too long, but actually hum, I didn't pushed the remaining changes to the master branch since I didn't finish reviewing the remaining strings haha ^^'

Is it possible to reopen the pull request or something like that ?

Also, I got some warnings about the same msg id being present multiple times. (particularly those for the wind and humidity "light, moderate and high" values if I remember right). Is this normal ?

**Comment by amit9838** [comment]
IMO msg id should be unique, if two msg_id are same then it must have context which makes it unique.
Would be nice if you open new pr for this.

**Comment by SpicyWasab** [comment]
Alright, I'll open another PR in a few hours when the translation looks good to me !
Yeah they have the same msg_id but a different context. I guess It's fine then !

**Pull request merged**
