### PR TITLE
Keyboard shortcuts added: -Open settings, -Open locations, -Refresh w…

### PR DESCRIPTION
**Pull request by francobattista**
…eather, using keyboard library

mousam.py file modified, added methods to create key listeners and listen the shortcuts.

I used "keyboard" library.

### CODE REVIEW

**Comment by amit9838** [comment]
Hi @francobattista  thanks making contribution, the keyboard package is not being maintained for now 
Screenshot 2024-05-07 at 2 33 44 PM
https://github.com/boppreh/keyboard

would be nice if you can try GTK's native keyboard methods, this makes the app lightweight

**Comment by francobattista** [comment]
Sure! I will change it.

**Comment by francobattista** [comment]
HI! I commited the new changes.

Now, Im using Gtk EventControllerKey to listen event keys.

**Review by amit9838 — APPROVED** [review]
Works fine,  Thanks @francobattista

**Pull request merged**
