### PR TITLE
Add nix shell and small run script

### PR DESCRIPTION
**Pull request by drunkbit**
I added a nix-shell and a small bash script.
The shell.nix file sets up a development environment for the project. It contains all the necessary dependencies to build and run the app without installing any packages. You can compare it to a Python virtualenv.
The run-app file is a small build script that does all the steps in one step and runs the app when it is done.

Nix information:
https://nixos.org/
https://nix.dev/manual/nix/2.18/

### CODE REVIEW

**Comment by amit-newstok** [comment]
Thats exciting, can pls make few more changes ?
Pls describe the steps to setup the dev env and build the app in the readme file.
Would be nice if you can share some screenshots or a short video of the process.

**Comment by amit9838** [comment]
Thats exciting, can pls make few more changes ?
Pls describe the steps to setup the dev env and build the app in the readme file.
Would be nice if you can share some screenshots or a short video of the process.
Thanks

**Comment by drunkbit** [comment]
Hey @amit9838, I have added a short guide to installing and using nix with some tips to the readme. I hope it is helpful 🙃

**Comment by drunkbit** [comment]
You can have a look at my fork, for a visual update: https://github.com/drunkbit/mousam/tree/nix-shell?tab=readme-ov-file#build

**Comment by amit9838** [comment]
hi @drunkbit it it working fine now? 
Would be nice if you can provide simple steps to setup this thing,also include the corresponding platforms like mac or linux.
thanks

**Pull request closed without merging**
