### PR TITLE
Hindi Translation Improvements

### PR DESCRIPTION
**Pull request by Scrambled777**
@amit9838 based on your comments [here](https://github.com/amit9838/mousam/pull/117#issuecomment-2109306364), I'm opening this draft.

I have made some changes based on your findings. Kindly, let me know if it's alright or does it need more modifications.

> here गतिशील refers some moving thing , also we can simple words for पृष्ठभूमि
> msgid "Dynamic Background"
> msgstr "गतिशील पृष्ठभूमि"

In my understanding, `Dynamic Background` depicts constantly changing background. Hence, the use of `गतिशील पृष्ठभूमि`. But, taken with context `Background changes based on current weather condition` perhaps, the use of word `Adaptive` will be more suitable. Previously I went with the individual string, but now I have translated together with context.

> also we can simple words for पृष्ठभूमि

I don't know how else to describe `Background`. As of now `पृष्ठभूमि` is the best word to use.

### CODE REVIEW

**Comment by amit9838** [comment]
I @Scrambled777, I can suggest you something,  may be you can try either chat-gpt or gemini for translation of strings,
if you provide the context in the prompt definitely you will get some good translations, with my past experience gemini's translation is better in some cases.
Also i  would suggest you to use sthan for locations (sthan is very common word)

**Comment by Scrambled777** [comment]
> I @Scrambled777, I can suggest you something, may be you can try either chat-gpt or gemini for translation of strings, if you provide the context in the prompt definitely you will get some good translations, with my past experience gemini's translation is better in some cases. Also i would suggest you to use sthan for locations (sthan is very common word)

Haven't interacted with AI LLM's till now. I check it out. 

I will revert back to `स्थान`.

Appreciate your reply.

**Comment by Scrambled777** [comment]
@amit9838 Can we merge this?

**Comment by amit9838** [comment]
O, I thought you are working on it, sure yes I'll merge it

**Review by amit9838 — APPROVED** [review]

**Comment by Scrambled777** [comment]
> @amit9838 Can we merge this?

I will keep looking for better wording and if I find something better, I will open new PR.

Cheers.

**Pull request merged**
